---
- name: create VMs
  hosts: localhost
  connection: local 
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: get VM disks
      command: "ls {{ vm_location }}"
      register: disks
      changed_when: "disks.rc != 0"

    - name: get list of VMs
      virt:
        command: "list_vms"
      register: vms

    - name: set image root password
      command: >
                virt-customize -a {{ vm_location }}/{{ guest_image }} --root-password password:{{root_pass}}

    - name: create vm
      command: >
                virt-install --import --name {{ item.key }}
                --memory {{ item.value.mem }} --vcpus {{ item.value.cpus }}
                --disk {{ vm_location }}/{{ guest_image }}
                --noautoconsole --os-variant {{ item.value.os_type }}                
      when: item.key not in vms.list_vms #
      with_dict: "{{ guests }}" #

    - name: start vm
      virt:
        name: "{{ item.key }}"
        state: running
      with_dict: "{{ guests }}" #

